sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
    
branches:
  only:
    - pg-hexo

# Start: Build Lifecycle
install:
  - npm install -g hexo-cli
  - npm install
  - npm install hexo-deployer-git --save

script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "Penley Wang"
  - git config user.email "penley.wang@outlook.com"
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy
# End: Build LifeCycle
